### ISSUE TITLE
log4j-core and log4j-api dependnecies should be test scoped.

### ISSUE THREAD

**Issue by Selaron** [urbanairship/java-library#100]
As it seems like log4j is only being directly references from within a single test class `src/test/java/com/urbanairship/api/client/UrbanAirshipClientTest.java` I don't see why `log4j-core` and `-api` dependencies are scoped `compile` instead of `test`.

Due to this, any project using the `java-client` also virtually depend on log4j.

**Comment by martin-vct** [comment]
Hi @Selaron,

Thank you for your feedback, we actually decided to remove it from the lib.
Feel free to update on the latest version (6.4.6).
