### ISSUE TITLE
"Interactive" field inside notifications?

### ISSUE THREAD

**Issue by Alotor** [urbanairship/java-library#29]
Hello,

Does the Java API support the "Interactive" field?

http://docs.urbanairship.com/api/ua.html#interactive-notifications

**Comment by pdxmele** [comment]
We're working on it! Should be in the next release.

**Comment by Alotor** [comment]
Nice. Thanks

**Comment by adelatorrefoss** [comment]
Hi! 
Is this bug solved? Have you some estimates when the next release will be available?

Thanks!

Antonio

**Comment by z0br0wn** [comment]
Yes, interactive notifications have been implemented!  Ran into some deployment issues today, but this should hopefully be sorted out and deployed tomorrow.  In the mean time, the updates are available on the github repo.

**Comment by z0br0wn** [comment]
Hi, thank you for your patience!  Interactive notifications have now been released in v0.3.3.
