### ISSUE TITLE
Does the API support the "Category" field from iOS8? 

### ISSUE THREAD

**Issue by cnordvik** [urbanairship/java-library#31]
http://docs.urbanairship.com/whats-new/july-2014-release.html

**Comment by z0br0wn** [comment]
Hi @cnordvik, apologies for the delay!  Are you asking if our client library supports `category`, or just the API in general?  The current release of the java library does not, however the next release (coming soon!) will indeed support the `category` field.  Our API does currently support the `category` field.

**Comment by z0br0wn** [comment]
Hi, v0.3.3 has now been released with iOS `category` support.  Thanks!
