### ISSUE TITLE
Not able to set connectionTimeout and socketTimeout

### ISSUE THREAD

**Issue by amol-gaikwad** [urbanairship/java-library#34]
APIClient builder or api methods such as 
```
public APIClientResponse<APIPushResponse> push(PushPayload payload)
```
should accept org.apache.http.params.BasicHttpParams so that we can set
- connectionTimeout
-  socketTimeout
- connectionRequestTimeout
- staleConnectionCheckEnabled

By default these values are set to 0 which means infinite timeout which causes performance problem in code using this client.

**Comment by z0br0wn** [comment]
Hi!  I've added BasicHttpParam support to APIClent in the new release (v0.3.3), please let me know if there are any issues or anything else I can help with.  Thanks!

**Comment by amol-gaikwad** [comment]
Thanks a lot Zach.
