### ISSUE TITLE
Optional being serialized instead of PushOption

### ISSUE THREAD

**Issue by jvdwesthuizen** [urbanairship/java-library#35]
When I add PushOptions to the PushPayload it serializes as: `..., "options":{"present":true}...`

Looks like it is just a missing call to `get()` in 
`jgen.writeObjectField("options", payload.getPushOptions());` [here](../blob/master/src/main/java/com/urbanairship/api/push/parse/PushPayloadSerializer.java)

**Comment by z0br0wn** [comment]
Hi, the expiry serialization bugs have been fixed and released in v0.3.3.  Please let me know if there are any other issues, thanks!
