### ISSUE TITLE
How can i send PushPayload with extra key

### ISSUE THREAD

**Issue by karunakaran-pt** [urbanairship/java-library#39]
@UrbanGitBot 

I am using the following to send push notifications 

String appKey = "appKey";
String appSecret = "appSecret";

// Setup an authenticated APIClient with your application key and
// application master secret.
APIClient apiClient = APIClient.newBuilder()
        .setKey(appKey)
        .setSecret(appSecret)
        .build();

// Setup a push payload to send to the API with our handy builders
PushPayload payload = PushPayload.newBuilder()
        .setAudience(Selectors.all())
        .setNotification(Notifications.notification("UA Push"))
        .setDeviceTypes(DeviceTypeData.of(DeviceType.IOS))
        .build();
// Try and send, handle anything that comes up
try {
    APIClientResponse<APIPushResponse> response = apiClient.push(payload);
    logger.info("Sent a push message!");
}
// Non 200 responses throw an APIRequestException. Check the documentation
// to debug your request.
catch (APIRequestException ex){
    logger.error("Non 200 request, checking error details and taking action");
}
// An underlying error occurred, most likely outside of the scope of the
// UA library, do some HTTP debugging
catch (IOException e){
    logger.error("Broken pipe what?");
}

I want to add a extra key like "key":"value" to the PushPayload. How can i do it ?

**Comment by pdxmele** [comment]
Hi there,
Please contact our support team at support@urbanairship.com, they will be happy to assist you with your questions about using the library. Thanks!
