### ISSUE TITLE
jackson dependency libraries are not updated to 2.7.0

### ISSUE THREAD

**Issue by CypraxPuch** [urbanairship/java-library#49]
the urbanairship java-client 1.0.0, is not updated with the jackson libraries, so, in runtime gives an Exception because don't find the objects.

this are the correct libraries:
groupId>com.fasterxml.jackson.core
artifactId>jackson-databind
version>2.7.0

groupId>com.fasterxml.jackson.core
artifactId>jackson-core
version>2.7.0

**Comment by madelgi** [comment]
Hi @CypraxPuch, sorry for the delayed response. Are you using a modern version of jackson alongside our library? If so, that is likely the cause of this problem. We are planning on updating the jackson dependency in the next release of the java library, hopefully sometime soon. In the meantime, feel free to fork the library and update the dependency yourself. Sorry for the inconvenience!
