### ISSUE TITLE
How to construct an implicit audience tag

### ISSUE THREAD

**Issue by meyumeapps** [urbanairship/java-library#51]
Hi,

I need to reduce the size of the request (we have a large number of tags) and would like to be able to construct an implicit compound selector:

http://docs.urbanairship.com/api/ua.html#compound-selectors

Can't seem to figure it out though?

**Comment by madelgi** [comment]
Hello @meyumeapps -- you can model the behavior of an implicit or selector like so:

```java
Selector orTags = Selectors.tags("tag1", "tag2", "tag3");
```

Note that this will still be serialized as an explicit or selector, i.e.:

```javascript
// Result after serialization
{
    "or": [
        {"tag": "tag1"},
        {"tag": "tag2"},
        {"tag": "tag3"},
    ]
}
```

Unfortunately, there is no analogous method for an "and" selector -- you must call `Selectors.tag` explicitly for each tag you wish to reference:

```java
Selector andTags = Selectors.and(
    Selectors.tag("tag1"),
    Selectors.tag("tag2"),
    Selectors.tag("tag3")
);
```

**Comment by madelgi** [comment]
Alternatively, if you know which tags you're sending to before constructing the request, you can define a segment and simply send to the segment:

```java
Selector tagSegment = Selectors.segment("my-segment"); 
```

This will actually reduce the size of the payload, but it requires that you build the segment ahead of time.

**Comment by meyumeapps** [comment]
Thanks @madelgi . Our tags are dynamic so I don't think the segment idea will work.

We are facing two problems:

- more than 1000 tags
- large message (> 2Mb)

Do you have any thoughts on how I can resolve these please?

**Comment by madelgi** [comment]
Hi @meyumeapps, do you mind explaining what your use case is? 1000 tags is an enormous query, and it's possible we offer a tool (perhaps named users) that would be more suitable for accomplishing your goals. 

There are a number of features we're trying to add to the java library right now, and I don't think we're going to get around to updating the serialization method for tags. However, we'd consider a patch if you want to submit something. Before that, though, we should see if there's is an implementation for your use case that doesn't use tags.

**Comment by meyumeapps** [comment]
Sure, we send notifications for our weather sites. Each site has a unique id.

Users subscribe to receive notifications for a weather site e.g. their home location or perhaps where they work.

We have over 6,000 sites and therefore have to send a push notification for each affected site. For example, if there was a severe weather warning covering much of the UK then we would want to send a push to UA listing the affected sites. Each tag would be a site id.

**Comment by madelgi** [comment]
Ah, interesting. This is a bit of an edge case, and I don't think our other features can help us out here. If you want to submit a PR that adds the implicit-or functionality, we'd be happy to review it. I'm sorry we couldn't help you more directly!

**Comment by meyumeapps** [comment]
Will certainly look at submitting the PR.

However, can you tell me if we would still hit the 1000 tag limit with the implicit-or functionality ?

**Comment by madelgi** [comment]
No such limit exists for the push API -- maybe you're thinking of the 1000 tag limit in place for segment creation?

Also, I'd recommend searching through or posting in [the forums](https://support.urbanairship.com/home). You may be able to get additional help there.

**Comment by meyumeapps** [comment]
This is the limit I was concerned about:

https://support.urbanairship.com/entries/109178196-What-are-the-limitations-to-the-Urban-Airship-Engage-API-

Have I misunderstood?

**Comment by madelgi** [comment]
That limit is advised, but it's not enforced by the push API. If you exceed it, you shouldn't encounter an error.

**Comment by meyumeapps** [comment]
Ah, excellent news, thank you 👍
