### ISSUE TITLE
PushDetailResponse java doc is missing

### ISSUE THREAD

**Issue by ms2scale** [urbanairship/java-library#55]
I somehow try to make sense of PushDetailResponse:

 private final long richDeletions;
 private final long richResponses;
 private final long richSends;
 private final long sends;
 private final long directResponses;
 private final long influencedResponses;

but there is absolutely no javadoc in the class file. What do these fields do / mean?

**Comment by pdxmele** [comment]
Hi there! Sorry about this, you've stumbled upon one our APIs that we no longer encourage people to use, so we have removed it from all of our docs. We will likely be removing it from the library shortly as well. Please contact our Support team if you have any other questions.

**Comment by ms2scale** [comment]
Why do you plan to remove this from the api? When is this change scheduled? Is there a replacement for this calls in a future version of the api?

**Comment by pdxmele** [comment]
Please contact our support team at support.urbanairship.com with your questions.
