### ISSUE TITLE
Missing notification_channel field in AndroidDevicePayload

### ISSUE THREAD

**Issue by pragmasoft-ua** [urbanairship/java-library#67]
Before completing the form below, please check the following:

- [*] You are using the most recent version of the library. 
- [ ] You are using a supported version of Java for that library version. 
- [ ] This issue is reproducible. 

I even checked the most recent snapshot 

## Expected Behavior
Push API supports notification_channel key in platform override section for Android. 

See

https://docs.urbanairship.com/api/ua/#schemas/androidoverrideobject/notification_channel

## Current Behavior

AndroidDevicePayload does not allow to specify notification_channel value, because correspondent property is missing

## Possible Solution

add notification_channel field to AndroidDevicePayload and correspondent serializer/deserializer

**Comment by devinsmythe** [comment]
This is supported as of version 4.3.0. Thanks for bringing it to our attention!
