### ISSUE TITLE
GCM registration

### ISSUE THREAD

**Issue by isonah** [urbanairship/java-library#71]
Hello,
I'm using your client to send notification to both iOS and Android platform.
For Apple, everything works as expected because I have the device token. However for Android, I only have the GCM Registration ID. Is there any way to use your client with that information in order to target one specific android device ?
BR,

**Comment by devinsmythe** [comment]
Hi @isonah There isn't a way to push directly to the GCM Reg ID.
The device token field is also deprecated so we recommend sending to the channel itself.
https://docs.airship.com/api/ua/#schemas/atomicselector/device_token

There are a few methods you can use to get the channel for each device_token / gcm_reg id. You could do a channel listing and check the channel / GCM reg id for the devices. 
https://github.com/urbanairship/java-library/blob/master/src/main/java/com/urbanairship/api/channel/ChannelRequest.java#L51

I'm not sure how you are gathering the GCM reg id for the devices but I'd recommend switching / also retrieving the channel ID for the devices.

**Comment by isonah** [comment]
Hello.
Ty for your answer.
I do retrieve channel id unstead now. But I still have something like : 

![image](https://user-images.githubusercontent.com/7563315/62953398-c1edd980-bded-11e9-8664-a2a0105cd532.png)

Any idea ?
Thanks in advance.

**Comment by aschuman0** [comment]
Hi @isonah - it looks like you have a installed and opted-in channel id there which you should be able to send to. If you're having issues with sending push or messages in general, please contact our support team at http://support.airship.com/ 
Thanks!
