### ISSUE TITLE
Would like the option to set EU datacenter baseURI during client configuration.

### ISSUE THREAD

**Issue by themistoklik** [urbanairship/java-library#72]
Following [docs](https://docs.airship.com/api/libraries/java/) while setting up a basic connection to client like so
```
return UrbanAirshipClient.newBuilder()
                .setKey(airshipProperties.key)
                .setSecret(airshipProperties.secret)
                .build()
```
Kept getting 401s. My mobile app developer colleagues were facing the same issue and got an email from support urging them (in the SDK) to set datacenter to EU programmatically. The client was invoking the US datacenter and our data was in EU, resulting in said errors. I thought I had to replicate the proposed solution in my server application. I can overwrite the client and use 

> .setClient(..)

but this is a little bit cryptic. I'd expect setting the correct baseUri to be exposed as configuration in the AsyncRequestClient or the docs referring to the client ovewrite specifically.

**Comment by krubasaur** [comment]
Hi there! Thanks for bringing this to our attention. We're looking into this and will post updates here as we have them.
