### ISSUE TITLE
NamedUserRequest only supports disassociating a single channel

### ISSUE THREAD

**Issue by breun** [urbanairship/java-library#83]
Before completing the form below, please check the following:

- [x] You are using the most recent version of the library. 
- [x] You are using a supported version of Java for that library version. 
- [x] This issue is reproducible. 

## Expected Behavior

https://docs.airship.com/api/libraries/java/#disassociate-named-user shows how to disassociate channels from a named user. The example is:

```
NamedUserRequest request = NamedUserRequest.newDisassociationRequest()
        .setChannel("ee4b5101-164c-485c-ad91-68b1d3d753cc", ChannelType.IOS)
        .setChannel("0ab7d6f0-0f61-4963-afe0-5ef53735b00d", ChannelType.ANDROID);

Response<String> response = client.execute(request);
````

This suggests it possible to disassociate multiple channels from a named user.

## Current Behavior

Looking at the contents of the `.setChannel` method I noticed it overwrites the `channel_id` entry in the payload map, so calling `.setChannel` the second time undoes the effect of the first call. So, only the channel referenced in the last call to `.setChannel` is actually disassociated.

## Possible Solution

Adjust either the documentation to reflect only a single channel can be disassociated per request, or allow the client to disassociate multiple channels using a single request.

## Steps to Reproduce

1. Create an instance of `NamedUserRequest` like this in a test:
```
NamedUserRequest request = NamedUserRequest.newDisassociationRequest()
        .setChannel("ee4b5101-164c-485c-ad91-68b1d3d753cc", ChannelType.IOS)
        .setChannel("0ab7d6f0-0f61-4963-afe0-5ef53735b00d", ChannelType.ANDROID);
```
2. Inspect this instance in a debugger.
3. See that the `payload` map only contains an entry for `0ab7d6f0-0f61-4963-afe0-5ef53735b00d`. There is no sign of `ee4b5101-164c-485c-ad91-68b1d3d753cc`.

**Comment by devinsmythe** [comment]
Thanks for submitting this issue. I'll take a look and work on implementing a fix for the next release.

**Comment by pdxmele** [comment]
It turns out our APIs don't allow this, so we unfortunately can't make it available in our Java library either.
