### ISSUE TITLE
ChannelTagRequest using Bearer authentication

### ISSUE THREAD

**Issue by youribonnaffe** [urbanairship/java-library#87]
## Expected Behavior

Being able to send a ChannelTagRequest using Bearer authentication.
The REST API seems to allow Bearer authentication for this endpoint (https://docs.airship.com/api/ua/#operation/api/channels/tags/post).

## Current Behavior

> Exception in thread "main" java.lang.IllegalStateException: Optional.get() cannot be called on an absent value
> 	at com.google.common.base.Absent.get(Absent.java:43)
> 	at com.urbanairship.api.client.UrbanAirshipClient.createHeaders(UrbanAirshipClient.java:97)
> 	at com.urbanairship.api.client.UrbanAirshipClient.executeAsync(UrbanAirshipClient.java:58)
> 	at com.urbanairship.api.client.UrbanAirshipClient.execute(UrbanAirshipClient.java:71)
> 	at com.urbanairship.api.client.UrbanAirshipClient.execute(UrbanAirshipClient.java:66)

Tested with Java SDK 5.0.0.

## Possible Solution

Override bearerTokenAuthRequired in ChannelTagRequest

```
ChannelTagRequest request = new ChannelTagRequest() {
            @Override
            public boolean bearerTokenAuthRequired() {
                return true;
            }
        }
         .addIOSChannels("XXX")
         .addTags("subscriptions", tags);
```

## Steps to Reproduce

With the following code (given valid credentials and channel id), the exception is produced.

```java
UrbanAirshipClient client = UrbanAirshipClient.newBuilder()
                .setBaseUri("https://go.airship.eu")
                .setKey("XXX")
                .setBearerToken("XXX")
                .build();

Set<String> tags = Set.of("tag");

ChannelTagRequest request = ChannelTagRequest.newRequest()
                .addIOSChannels("XXX")
                .addTags("subscriptions", tags);

Response<String> response = client.execute(request);
```

**Comment by hameno** [comment]
Same for named user, actually: you currently cannot use secure tag groups with this client bacause of this "bug"
