### ISSUE TITLE
CustomEventUser does not support NamedUserId

### ISSUE THREAD

**Issue by bgoncharenko** [urbanairship/java-library#89]
According to the documentation (https://docs.airship.com/api/ua/#schemas/customeventobject), a custom event request should accept a NamedUserId. However, the current implementation (https://github.com/urbanairship/java-library/blob/master/src/main/java/com/urbanairship/api/customevents/model/CustomEventUser.java) allows setting only Channels. Please consider changing the model, so that it supports NamedUserIds.

**Comment by devinsmythe** [comment]
@bgoncharenko This should be supported as of version 6.0.0.
