### ISSUE TITLE
ChannelType.EMAIL in NamedUserRequest BUG

### ISSUE THREAD

**Issue by lagonzalezr** [urbanairship/java-library#90]
According to api https://docs.airship.com/api/ua/#operation/api/named_users/associate/post 
I should not set type `email` with namedUser Association. If I set it as null it throws a null pointer exception inside the client
Example with type:
NamedUserRequest requestNamed = NamedUserRequest.newAssociationRequest()
                .setChannel(userData.getChannelId(), ChannelType.EMAIL)
                .setNamedUserId("3647824");

Current Behavior:
 
{
    "ok": false,
    "error": "Could not parse request body.",
    "error_code": 40002,
    "details": {
        "error": "Unrecognized device type email"
    }
}
Example with type null:
NamedUserRequest requestNamed = NamedUserRequest.newAssociationRequest()
                .setChannel(userData.getChannelId(), null)
                .setNamedUserId("3647824");

Current Behavior:
throws a NullpointerException.

ChannelType is a required field in the client method call but not for the api 
https://github.com/urbanairship/java-library/blob/bf1d9c4ffeb41f50043677cde01f1552c70984e7/src/main/java/com/urbanairship/api/nameduser/NamedUserRequest.java#L66

**Comment by devinsmythe** [comment]
@lagonzalezr This issue should be resolved in 6.1.0. You shouldn't have a problem when setting ChannelType.EMAIL in NamedUserRequest. Let me know if you have any issues.
