### ISSUE TITLE
Improve Precoditions.checkNotNull usage for Optionals

### ISSUE THREAD

**Issue by meierjan** [urbanairship/java-library#92]
https://github.com/urbanairship/java-library/blob/0e79dbea8f4f227b919220bb666f8acdcbcbd8c6/src/main/java/com/urbanairship/api/client/UrbanAirshipClient.java#L94

The precondition won't fail as it won't ever be null.

>   \* @throws IllegalStateException if the instance is absent ({@link #isPresent} returns {@code
>   \*     false}); depending on this <i>specific</i> exception type (over the more general {@link
>   \*     RuntimeException}) is discouraged

**Comment by devinsmythe** [comment]
@meierjan Thank you for pointing that out. I'll work on a fix for this in our next release.
